[package]
name = "ci-example"
version = "0.1.0"
authors = ["Boyu Yang <yangby@cryptape.com>"]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]
libc = "0.2.101"

[build-dependencies]
bindgen = "0.59.1"
cc = "1.0.70"
cmake = "0.1.45"
