name: Bors
on:
  pull_request:
    types: [labeled]
jobs:
  auto-merge:
    if: ${{ github.event.label.name == 'approved' }}
    name: Auto Merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.TOKEN_ACTIONS_BOT }}
          script: |
            github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'bors merge'
            })
